# Generated by Django 3.0 on 2020-12-25 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201225_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='categorynew',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.Listing'),
        ),
        migrations.AddField(
            model_name='categorynew',
            name='parents',
            field=models.ForeignKey(blank=True, default=1, limit_choices_to={'parents__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='auctions.CategoryNew'),
        ),
    ]
