# Generated by Django 3.0 on 2021-01-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201225_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='subcategory',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.DeleteModel(
            name='CategoryNew',
        ),
    ]
