# Generated by Django 3.0 on 2021-01-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210101_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='active_count',
            field=models.IntegerField(default=0),
        ),
    ]
