# Generated by Django 3.0 on 2021-01-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210112_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_one', models.ImageField(upload_to='images/')),
                ('image_two', models.ImageField(upload_to='images/')),
                ('image_three', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='listing',
            name='image',
        ),
    ]
