# Generated by Django 3.0 on 2021-01-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210113_1622'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AddField(
            model_name='listing',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
