# Generated by Django 3.0 on 2021-01-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210113_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='image_one',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='image_three',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='image_two',
        ),
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
