# Generated by Django 3.0 on 2021-01-13 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210113_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='subcategory',
        ),
    ]
