# Generated by Django 3.0 on 2021-01-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='listing',
            name='subcategory',
            field=models.CharField(default='', max_length=64),
        ),
    ]
